// src/auditors/stack-scanner.ts — Heuristic project scanner for sla init

import * as fs from "fs";
import * as path from "path";
import type {
  StackDetectionResult,
  SLARulesConfig,
  SLARule,
} from "../types.js";

export class StackScanner {
  private rootDir: string;
  private packageJson: Record<string, any>;

  constructor(rootDir: string = process.cwd()) {
    this.rootDir = rootDir;
    this.packageJson = this.loadPackageJson();
  }

  /**
   * Detect the technology stack used in the project.
   */
  detect(): StackDetectionResult {
    const deps = {
      ...this.packageJson.dependencies,
      ...this.packageJson.devDependencies,
    };

    return {
      projectName:
        this.packageJson.name ?? path.basename(this.rootDir) ?? "unknown",
      hasNextJs: !!(
        deps["next"] ||
        this.exists("next.config.js") ||
        this.exists("next.config.mjs") ||
        this.exists("next.config.ts")
      ),
      hasSupabase: !!(
        deps["@supabase/supabase-js"] ||
        deps["@supabase/auth-helpers-nextjs"]
      ),
      hasPrisma: !!(deps["@prisma/client"] || this.exists("prisma/schema.prisma")),
      hasDrizzle: !!(deps["drizzle-orm"] || deps["drizzle-kit"]),
      hasAWS: !!(
        deps["@aws-sdk/client-s3"] ||
        deps["@aws-sdk/client-lambda"] ||
        deps["@aws-sdk/client-sqs"] ||
        this.exists("template.yaml") ||
        this.exists("serverless.yml")
      ),
      hasReact: !!(deps["react"] || deps["react-dom"]),
      hasTRPC: !!(deps["@trpc/server"] || deps["@trpc/client"]),
      hasTailwind: !!(
        deps["tailwindcss"] || this.exists("tailwind.config.ts")
      ),
      hasZod: !!deps["zod"],
      hasVitest: !!(deps["vitest"] || this.packageJson.scripts?.test?.includes("vitest")),
      hasDocker: this.exists("Dockerfile") || this.exists("docker-compose.yml"),
    };
  }

  /**
   * Generate a rules config tailored to the detected stack.
   */
  generateRules(stack: StackDetectionResult): SLARulesConfig {
    const constraints: SLARule[] = [];

    if (stack.hasNextJs) {
      constraints.push(...this.nextJsRules());
    }
    if (stack.hasSupabase) {
      constraints.push(...this.supabaseRules());
    }
    if (stack.hasPrisma) {
      constraints.push(...this.prismaRules());
    }
    if (stack.hasDrizzle) {
      constraints.push(...this.drizzleRules());
    }
    if (stack.hasAWS) {
      constraints.push(...this.awsRules());
    }
    if (stack.hasReact) {
      constraints.push(...this.reactRules());
    }
    if (stack.hasTRPC) {
      constraints.push(...this.trpcRules());
    }

    // Universal security rules always included
    constraints.push(...this.universalSecurityRules());

    return {
      version: "2.0",
      project: stack.projectName,
      description: `Auto-generated by SLA Init — ${new Date().toISOString()}`,
      enforcementLevel: "block",
      llmProvider: "anthropic",
      ignorePatterns: ["**/*.test.ts", "**/*.spec.ts", "**/__mocks__/**"],
      constraints,
    };
  }

  // ─── Rule Packs ─────────────────────────────────────────────────────────────

  private nextJsRules(): SLARule[] {
    return [
      {
        id: "NEXT-001",
        name: "Server Action Auth Guard",
        category: "security",
        severity: "CRITICAL",
        pattern: {
          regex: "^export async function \\w+\\(",
          scope: "**/app/**/actions.ts",
        },
        requirement:
          "All Server Actions must authenticate the user before executing business logic.",
        advice:
          "Add `const session = await auth(); if (!session) throw new Error('Unauthorized');` at the top.",
        autoFix: { useLLM: true, templateRef: "SECURITY-SERVER-ACTION" },
        tags: ["nextjs", "auth"],
      },
      {
        id: "NEXT-002",
        name: "No Service Role Key on Client",
        category: "security",
        severity: "CRITICAL",
        pattern: {
          regex: "SERVICE_ROLE_KEY",
          scope: "**/components/**",
        },
        requirement:
          "Never expose the Supabase Service Role Key to client-side bundles.",
        advice: "Use `createServerActionClient` in a Server Action instead.",
        autoFix: { useLLM: true, templateRef: "SECURITY-SERVICE-ROLE" },
        tags: ["nextjs", "supabase", "secrets"],
      },
      {
        id: "NEXT-003",
        name: "Zod Validation on Server Actions",
        category: "architecture",
        severity: "HIGH",
        pattern: {
          regex: "export async function \\w+\\(formData",
          scope: "**/app/**/actions.ts",
        },
        requirement:
          "All Server Actions accepting FormData must validate input with a Zod schema.",
        advice:
          "Define `const schema = z.object({...})` and call `schema.parse(...)` before using the data.",
        autoFix: { useLLM: true },
        tags: ["nextjs", "validation"],
      },
    ];
  }

  private supabaseRules(): SLARule[] {
    return [
      {
        id: "SUPA-001",
        name: "RLS Bypass Detection",
        category: "security",
        severity: "CRITICAL",
        pattern: {
          regex: "DISABLE ROW LEVEL SECURITY",
        },
        requirement:
          "Disabling RLS is forbidden. All tables must have Row Level Security enabled.",
        advice:
          "Use a `SECURITY DEFINER` function in the `internal` schema for admin operations.",
        tags: ["supabase", "database", "security"],
      },
      {
        id: "SUPA-002",
        name: "No String Concatenation in RPC",
        category: "security",
        severity: "HIGH",
        pattern: {
          regex: "supabase\\.rpc\\(['\"][\\w]+['\"],.*\\+",
        },
        requirement:
          "Do not concatenate strings in Supabase RPC calls — use parameterized object arguments.",
        advice: "Replace string concatenation with `{ param: value }` objects.",
        autoFix: { useLLM: true },
        tags: ["supabase", "sql-injection"],
      },
    ];
  }

  private prismaRules(): SLARule[] {
    return [
      {
        id: "PRISMA-001",
        name: "No Direct Prisma in Components",
        category: "architecture",
        severity: "HIGH",
        pattern: {
          regex: "import.*prisma.*from",
          scope: "**/components/**",
        },
        requirement:
          "Components must not import Prisma directly. Use Server Actions or tRPC procedures.",
        advice:
          "Move the data-fetching logic to `app/actions.ts` or a tRPC router.",
        autoFix: { useLLM: true, templateRef: "ARCH-NO-PRISMA-CLIENT" },
        tags: ["prisma", "architecture"],
      },
      {
        id: "PRISMA-002",
        name: "No Raw SQL in Prisma",
        category: "security",
        severity: "HIGH",
        pattern: {
          regex: "prisma\\$queryRaw`.*\\$\\{",
        },
        requirement:
          "Avoid dynamic interpolation in `$queryRaw`. Use `$queryRawUnsafe` only with sanitized inputs or switch to the fluent API.",
        advice:
          "Use `prisma.model.findMany({ where: {...} })` instead of raw SQL.",
        tags: ["prisma", "sql-injection"],
      },
    ];
  }

  private drizzleRules(): SLARule[] {
    return [
      {
        id: "DRIZZLE-001",
        name: "No Raw SQL Strings",
        category: "security",
        severity: "MEDIUM",
        pattern: {
          regex: "db\\.execute\\(sql`[^`]*\\$\\{",
        },
        requirement:
          "Avoid dynamic template literals in `db.execute`. Use the Drizzle fluent query builder.",
        advice: "Use `db.select().from(table).where(eq(table.col, value))`.",
        autoFix: { useLLM: true, templateRef: "TRANSFORM-DB-001" },
        tags: ["drizzle", "sql-injection"],
      },
    ];
  }

  private awsRules(): SLARule[] {
    return [
      {
        id: "AWS-001",
        name: "Lambda ARM64 Enforcement",
        category: "finops",
        severity: "MEDIUM",
        pattern: {
          regex: "Architecture:\\s*['\"]x86_64['\"]",
          scope: "**/template.yaml",
        },
        requirement:
          "All Lambda functions must use `arm64` architecture for ~20% cost savings.",
        advice: "Replace `Architecture: x86_64` with `Architecture: arm64`.",
        autoFix: { replace: "Architecture: arm64" },
        tags: ["aws", "lambda", "finops"],
      },
      {
        id: "AWS-002",
        name: "No Public S3 Buckets",
        category: "security",
        severity: "CRITICAL",
        pattern: {
          regex: "PublicReadAccess:\\s*true",
        },
        requirement: "S3 buckets must not be publicly accessible by default.",
        advice:
          "Use a CloudFront distribution with an Origin Access Identity instead.",
        autoFix: { replace: "PublicReadAccess: false" },
        tags: ["aws", "s3", "security"],
      },
      {
        id: "AWS-003",
        name: "Fat Lambda Prevention",
        category: "architecture",
        severity: "HIGH",
        pattern: {
          regex: "if\\s*\\(event\\.path\\s*===.*if\\s*\\(event\\.path\\s*===",
          scope: "**/lambdas/**",
        },
        requirement:
          "One Lambda per route. Do not build routers inside a single Lambda handler.",
        advice:
          "Split into multiple function files. Each handler should have a single purpose.",
        autoFix: { useLLM: true },
        tags: ["aws", "lambda", "architecture"],
      },
    ];
  }

  private reactRules(): SLARule[] {
    return [
      {
        id: "REACT-001",
        name: "No useEffect for Data Fetching",
        category: "performance",
        severity: "MEDIUM",
        pattern: {
          regex: "useEffect\\([^)]*fetch\\(",
          scope: "**/components/**",
        },
        requirement:
          "Do not use `useEffect` for initial data fetching. Use React Query, SWR, or Server Components.",
        advice:
          "Move fetch logic to a Server Component or use `useQuery` from TanStack Query.",
        autoFix: { useLLM: true },
        tags: ["react", "performance"],
      },
      {
        id: "REACT-002",
        name: "PII Taint API Enforcement",
        category: "security",
        severity: "HIGH",
        pattern: {
          regex: "return\\s*\\{[^}]*(password|ssn|creditCard|token)[^}]*\\}",
          scope: "**/app/api/**",
        },
        requirement:
          "Sensitive fields must be wrapped with `experimental_taintUniqueValue` before returning to clients.",
        advice:
          "Call `experimental_taintUniqueValue('msg', obj, obj.password)` at the data-fetching layer.",
        autoFix: { useLLM: true, templateRef: "SEC-TAINT-003" },
        tags: ["react", "security", "pii"],
      },
    ];
  }

  private trpcRules(): SLARule[] {
    return [
      {
        id: "TRPC-001",
        name: "tRPC Procedure Auth Middleware",
        category: "security",
        severity: "HIGH",
        pattern: {
          regex: "publicProcedure\\.mutation\\(",
          scope: "**/server/routers/**",
        },
        requirement:
          "Mutation procedures that modify data must use `protectedProcedure`, not `publicProcedure`.",
        advice:
          "Change `publicProcedure.mutation` to `protectedProcedure.mutation` for authenticated endpoints.",
        autoFix: { replace: "protectedProcedure.mutation(" },
        tags: ["trpc", "auth"],
      },
    ];
  }

  private universalSecurityRules(): SLARule[] {
    return [
      {
        id: "SEC-001",
        name: "No Hardcoded Secrets",
        category: "security",
        severity: "CRITICAL",
        pattern: {
          regex:
            "(password|secret|api_key|apikey|token)\\s*=\\s*['\"][A-Za-z0-9+/=_-]{8,}['\"]",
        },
        requirement:
          "Never hardcode secrets in source code. Use environment variables or a secrets manager.",
        advice:
          "Replace the literal value with `process.env.YOUR_SECRET_NAME`.",
        tags: ["security", "secrets"],
      },
      {
        id: "SEC-002",
        name: "No process.env in Client Code",
        category: "security",
        severity: "HIGH",
        pattern: {
          regex: "process\\.env\\.[A-Z_]+",
          scope: "**/components/**",
        },
        requirement:
          "Do not read `process.env` directly in client components. Use the `env.ts` validation module.",
        advice:
          "Access env vars through a validated `env` object exported from `@/lib/env.ts`.",
        autoFix: { useLLM: true },
        tags: ["security", "env"],
      },
      {
        id: "SEC-003",
        name: "No eval() Usage",
        category: "security",
        severity: "CRITICAL",
        pattern: {
          regex: "\\beval\\s*\\(",
	  scope: "**/!(stack-scanner).ts",
        },
        requirement:
          "`eval()` is forbidden due to code injection risk. Use safer alternatives.",
        advice:
          "Replace `eval()` with `JSON.parse()`, `Function` constructors only if absolutely necessary, or refactor the logic.",
        tags: ["security"],
      },
    ];
  }

  private loadPackageJson(): Record<string, any> {
    const pkgPath = path.join(this.rootDir, "package.json");
    if (!fs.existsSync(pkgPath)) return {};
    try {
      return JSON.parse(fs.readFileSync(pkgPath, "utf8"));
    } catch {
      return {};
    }
  }

  private exists(relPath: string): boolean {
    return fs.existsSync(path.join(this.rootDir, relPath));
  }
}
